### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by pavlos256** [James-Livesey/atto#21]
Atto has problems with some Unicode characters (like emoji).

Example program:

```basic
10 PRINT "Καλημέρα 😄"
```

[test.atto.txt](https://github.com/James-Livesey/atto/files/7226021/test.atto.txt)

![2021-09-24_16-37](https://user-images.githubusercontent.com/311595/134683688-7ea87657-0c06-41a1-98ee-aee5c03f7bee.png)

The problem is that when accessing chars like `text[9]`, the emoji is returned in two parts (positions 9 & 10). A workaround is to do:

`var chars = Array.from(text);`

Then `chars[9]` will return "😄".

Applying this change to `term.js:print()` and `canvas.js:drawText()` seems to be enough to make the above program run correctly. The program listing still has problems though, because of the `hid.js:render` function.

**Comment by James-Livesey** [comment]
Today I learned about the `Array.from` function for Unicode conversion! Thanks for letting me know about this bug, though. I do think that emoji would be a welcome addition to atto! I'll look into this and let you know when it's all fixed.

**Comment by James-Livesey** [comment]
All issues with rendering emoji should be solved now! Hopefully this will be a great addition for younger users of atto who want to add emojis to their programs. I remember users of educational programming languages such as Hopscotch heavily relying on emoji to convey pictorial meaning, so there's no doubt that emojis will be used a lot in atto!
