### ISSUE TITLE
GOTO should fall-through when given an invalid line

### ISSUE THREAD

**Issue by skx** [James-Livesey/atto#4]
Consider this program:

     10 PRINT "OK"
     20 GOTO 1

This reports an error ("cannot goto a nonexistant line"), but I think it should fall-through.  Reporting an invalid line is probably the correct choice with:

     10 PRINT "BLAH"
     20 GOTO 3000
     2000 PRINT "BLAH"

I guess here the expectation is that GOTO should go to the named line, and if it isn't present the next one that _is_ there.  But be limited by the upper-bound of lines that was used.

**Comment by James-Livesey** [comment]
Thanks for the issue! Haven't really thought about this mechanic to BASIC myself. Seems to be a great improvement, so I've created a pull request and I'm about to merge it!

**Comment by James-Livesey** [comment]
All merged; just give GitHub Pages a few minutes to get its act together, and then once you've hard reloaded, it should all be working!
